version: '3.7'

volumes:
  rent-db:

services:
  rent-postgres:
    container_name: rent-db
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rent-db
    volumes:
      #      - ts-db:/var/lib/postgresql/data
      #      - ./data:/var/lib/postgresql/data
      - rent-db:/var/lib/postgresql/data
    ports:
      - "5450:5432"